### ISSUE TITLE
[코멘트 요청-컴포넌트 구조]

### ISSUE THREAD

**Issue by f-ffff-f** [zeze88/imageshare#27]
프로젝트의 컴포넌트 구조가 잘 짜인건지 궁금합니다. 개발중에 클라이언트 사이드에서 데이터가 서로 엉켜서 의도치 않은 결과를 만든적이 많아서요.
리액트에서 코드가 실행 되는 순서가 아직도 확실하게 개념이 잡히지 않는데 무슨 키워드로 공부를 해보면 좋을까요? useEffect 메소드가 제 생각대로 동작하지 않는 경험을 많이 했습니다.

**Comment by keimindev** [comment]
안녕하세요. 유강현님, 정재연님 이번 주차 프로젝트 코멘트 답변을 드릴 정민경이라고 합니다. 
이번 프로젝트 만드시느라 너무 수고가 많으셨어요. 깔끔한 UI와 구조가 눈에 쏙 들어오네요 

코멘트 요청 주신부분에 대해 답변 드리겠습니다. 

- 현재 프로젝트의 구조는 괜찮습니다. component의 경우에는 작은 부분까지 세세하게 나누셔서 저는 게인적으로 이런 구조가 팀 협업 할 때 코드를 읽기 쉽고 좋다고 생각합니다. 하지만 이것보다 더 큰 프로젝트가 진행이 될 때는 컴포넌트간의 데이터 전달 부분이 복잡해질 우려는 있습니다. 이런 부분이 제대로 안 잡혀 있다면 정말 단위까지 구조를 쪼개서 만드는 건 비추합니다. 컴포넌트 구조 관련한 공부는 깃헙에 있는 다양하고 좋은 오픈소스를 많이 보시라고 추천드립니다. 그러면 자연스레 구조에 대한 공부가 될 실 것 같습니다. 그리고 프로젝트를 시작 전에 구조에 대한 고민과 공부를 많이 하시는 건 정말 좋은 것 같아요! 👍🏻

- 클라이언트 사이드에서 데이터가 엉키는 부분은 리액트 ``데이터 전달``에 대한 공부를 더 해보시면 될 것 습니다. 공식문서 추천드려요! 

- useEffect가 제대로 동작하지 않는 경험이라는 것이 어떤 경우였는지 모르겠지만 제 경험에 미루어보자면 보통은 props가 제대로 전달되지 않아서 혹은 부모 컴포넌트가 아닌 자식 컴포넌트에서 useEffect로 무언가를 하려고하면 동작이 안 될 경우가 있었던 것 같습니다. 혹은 조건부 렌더링이 잘 못 된 경우도 있고요. useEffect가 쉬운듯하지만 공부하기 어렵고 쓰기 까다롭게 여겨지는 메소드입니다.  리액트의 ``라이프 사이클``부분을 공부하시면 리액트의 코드실행과 useEffect를 더 잘 이해하실 수 있습니다. 



😊 이상 저의 코멘트는 마무리하겠습니다! 빡빡한 일정이지만 건강도 꼭! 챙기시면서 무사히 진행하시길 기원합니다! 정말 고생 많으셨어요!!!

**Comment by f-ffff-f** [comment]
> 프로젝트의 컴포넌트 구조가 잘 짜인건지 궁금합니다. 개발중에 클라이언트 사이드에서 데이터가 서로 엉켜서 의도치 않은 결과를 만든적이 많아서요.
> 리액트에서 코드가 실행 되는 순서가 아직도 확실하게 개념이 잡히지 않는데 무슨 키워드로 공부를 해보면 좋을까요? useEffect 메소드가 제 생각대로 동작하지 않는 경험을 많이 했습니다.

감사합니다 많은 도움이 됐습니다!
